<!doctype html>
<html class="no-js" lang="">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>1am Club</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="/css/main.css">
		<link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div class="main_header">{{> header }}</div>
		<div class="main_navigator">{{> nav }}</div>
		<div class="main_content">{{{ body }}}</div>
	</body>
</html>